
- name: Install dependencies
  apt:
      name: [
      "ca-certificates", 
      "curl",
      "gnupg", 
      "python3-pip"
      ]
      state: latest

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker
  apt:
      name: [
        'docker-ce', 
        'docker-ce-cli', 
        'containerd.io'
      ]
      state: latest
      update_cache: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  
- name: Add vagrant to docker group
  user:
      name: vagrant
      groups: docker
      append: yes

# installing requests & docker allows the community.general.docker_swarm plugin to work 
- name: Install docker-compose via pip
  pip:
    name: ['docker-compose']
    state: latest