---
- hosts: mitm-client
  become: yes
  tasks:
  - name: Copy deps scripts
    ansible.posix.synchronize:
      src: "../dep_fetchers"
      dest: /home/vagrant/


- hosts: mitm-server
  become: yes
  roles:    
    - role: mitm-server/copy_logs
      vars:
        - mitmdump_log_file: ../logs/init.log
        - url_log_file: ../logs/url.log
      

- hosts: mitm-client
  become: yes
  tasks:
    - name: Build NLTK container
      make:
        chdir: dep_fetchers/nltk
        target: get_nltk_data_build


- hosts: mitm-server
  become: yes
  roles:    
    - role: mitm-server/copy_logs
      vars:
        - mitmdump_log_file: ../logs/nltk/build/init.log
        - url_log_file: ../logs/nltk/build/url.log


- hosts: mitm-client
  become: yes
  tasks:
    - name: Get NLTK data
      make:
        chdir: dep_fetchers/nltk
        target: get_nltk_data_download


- hosts: mitm-server
  become: yes
  roles:    
    - role: mitm-server/copy_logs
      vars:
        - mitmdump_log_file: ../logs/nltk/mitm.log
        - url_log_file: ../logs/nltk/url.log


- hosts: mitm-client
  become: yes
  roles:    
    - role: mitm-client/clam_scan
      vars:
      dir_to_scan: dep_fetchers/nltk/content
      log_dir: ../logs/nltk

  
- hosts: mitm-client
  become: yes
  roles:    
    - role: mitm-client/file_permissions
      vars:
      dir_to_scan: dep_fetchers/nltk/content
      log_dir: ../logs/nltk
 
