---

# to run & set up all machines
- hosts: mitm-server
  become: yes
  roles:
    - mitm-server/route

# Fetch the image on the vagrant host - means that it is retained between deployments
- hosts: mitm-client
  become: yes
  roles:
    - mitm-client/route
